export * from './country';

export const text = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In scelerisque eros nunc, ut imperdiet nisi consequat et. In ac nisl quis augue sollicitudin ultrices eu eget quam. Maecenas sit amet imperdiet ante, et facilisis dolor. Donec diam ipsum, imperdiet vel pulvinar id, viverra ac tortor. Nunc ut eros sollicitudin, ultricies neque vel, sodales sem. Integer egestas nisi eu justo molestie efficitur. Mauris tincidunt sit amet eros vitae condimentum. Curabitur bibendum ac velit dapibus facilisis. In ornare pellentesque erat",
    "eu sodales sem imperdiet sed. Aliquam sit amet turpis nec purus feugiat vulputate. Proin quis ultricies risus. Ut a tortor a orci suscipit tincidunt. Ut aliquam metus ut arcu vestibulum aliquet. Cras venenatis mi tellus, eget semper ligula pulvinar sit amet. Ut vel arcu id nibh mollis blandit et sed lorem.",
    "Sed congue lacus ut nibh lacinia pulvinar. Praesent et eros dui. Donec lobortis pretium massa. Mauris faucibus ex accumsan leo varius vulputate. In rhoncus ex vel est pellentesque, id mollis lorem fringilla. Ut lobortis erat nec diam condimentum, in hendrerit neque facilisis.",
    "Vivamus pellentesque non eros et malesuada. In sollicitudin rhoncus turpis in imperdiet. Ut sit amet finibus dolor, quis aliquam mi. Sed eget ante mauris. Aliquam erat volutpat. Nullam at rutrum nisi. Ut non urna dapibus, sollicitudin ex vitae, suscipit ipsum.",
    "Sed sagittis arcu nibh, viverra imperdiet neque consectetur vitae. Cras pellentesque suscipit lorem, vitae mollis quam mollis in. Etiam et felis nibh. Integer aliquam odio felis, eget bibendum neque laoreet et. Integer at pellentesque odio. Curabitur felis magna, iaculis id orci et, sagittis ullamcorper leo. Praesent et orci vulputate, suscipit eros sit amet, tristique sapien.",
    "Curabitur quis suscipit velit, eu lacinia tellus. Morbi sodales nulla at erat blandit dictum ac at leo. Curabitur eleifend sagittis justo scelerisque feugiat. Vivamus placerat lorem justo. Suspendisse aliquam",
    "est sed nulla iaculis ornare et at massa. Vivamus fringilla tristique blandit. Morbi facilisis pretium orci quis congue. Nulla placerat lobortis ex eget pretium. Donec efficitur aliquam augue, ut eleifend ex mattis eget. In dapibus iaculis ex, eu aliquam sapien convallis et. Donec malesuada metus libero",
    "eu suscipit ipsum condimentum non. Sed ullamcorper fermentum ultricies. Aenean sit amet dapibus eros. Etiam rutrum quam in dolor dignissim cursus. Fusce condimentum, neque nec mattis venenatis, massa metus ornare tortor, eu hendrerit purus leo ut libero.",
    "Duis pellentesque tortor quam, et eleifend arcu faucibus varius. Sed luctus vitae nunc lacinia malesuada. Nullam porta lectus scelerisque ante interdum, ac ultrices dolor interdum. Nunc dapibus",
    "elit non odio consequat imperdiet. Ut scelerisque, tellus sed consequat fermentum, nunc magna faucibus nulla, at euismod ipsum urna a augue",
];

export const name = [
    "Sajra Margareta",
    "Khamisi Kailee",
    "Lexus Kayley",
    "Mark Rositsa",
    "Phuntsok Ramesh",
    "Heidi Wilkins",
    "Jose Pierce",
    "Wade Waters",
    "Javier Jones",
    "Margie Stokes",
    "Rick Graves",
    "Toni Mcgee",
    "Don Garcia",
    "Rufus Knight",
    "Stephen Bass",
    "Madara Adile",
    "Achelous Abegail",
    "Blandina Gioacchino",
    "Mariyam Lyndsea",
    "Gunnar Erhan",
];

export const address = [
    "Jl Bahagia Permai Raya 29, Jawa Barat",
    "Lindeteves Trade Center GF 1 Blok C6/6, Lindeteves Trade Center GF 1 RB 45 / C31 No 8, Dki Jakarta",
    "Jl Mangga Bolong Kompl Yon Zikon 11 RT 001/18 Srengseng S, Jakarta",
    "Jl Letjen South Parman Mal Ciputra, Dki Jakarta",
    "Jl Raya Panglima Sudirman 44,Tisnonegaran",
    "Kompl Makassar Mall C/3 B-C-D",
    "Jl By Pass Kediri",
    "Jl Boulevard Diponegoro 105 Supermal Karawaci Lt Dasar,Lippo Karawaci",
    "Jl Letjen Jamin Ginting 28, Sumatera Utara",
    "Kompl Buluh Indah 9 AB",
];

export const email = [
    "sblack@mac.com",
    "feamster@yahoo.ca",
    "sokol@live.com",
    "jbarta@optonline.net",
    "shaffei@hotmail.com",
    "ghaviv@aol.com",
    "michiel@gmail.com",
    "gtewari@sbcglobal.net",
    "shaffei@sbcglobal.net",
    "ardagna@optonline.net",
    "jbarta@live.com",
    "emmanuel@optonline.net",
    "aegreene@live.com",
    "petersen@msn.com",
    "bjoern@live.com",
    "skythe@live.com",
    "heroine@outlook.com",
    "miturria@optonline.net",
    "dburrows@icloud.com",
    "seurat@aol.com",
    "joehall@msn.com",
    "balchen@verizon.net",
    "dwheeler@hotmail.com",
    "oevans@live.com",
];

export const brand = [
    "premiertidy",
    "velovery",
    "dommild",
    "workingfive",
    "lexquiz",
    "passpros",
    "glassfoxy",
    "dfcool",
    "vinenvy",
    "allaboutlust",
    "quantumcalm",
    "ifmust",
    "txaver",
    "bymany",
    "learnrosy",
    "crystalflip",
    "joezing",
    "switchgift",
    "wxrich",
    "jordanweal",
    "fedooze",
    "demouber",
    "djwear",
    "bestoffull",
];